import type { BookScreenItem } from '../services/types';

// Локальні mock-дані для демо/fallback. ID — у форматі GUID,
// як і в бекенді (Postgres uuid).
export const ALL_ITEMS: BookScreenItem[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    title: 'Гаррі Поттер і філософський камінь',
    year: 2001,
    genre: 'Фентезі',
    country: 'Велика Британія',
    poster:
      'https://m.media-amazon.com/images/M/MV5BNmQ0ODBhMjUtNDRhOC00MGQzLTk5MTAtZTJjOWQ1NjkxZmQ1XkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_SX300.jpg',
    bookRating: 9.2,
    filmRating: 8.5,
    description: 'Хлопчик-сирота дізнається, що він чарівник, і вступає до школи Гоґвортс.',
    author: 'J. K. Rowling',
    hasMap: true,
    filmYear: 2001,
    director: 'Chris Columbus',
    bookSummary: 'Перша екранізація культової книги, що показує вступ Гаррі до Гоґвортсу. Його знайомство з друзями і світом магії.',
    filmSummary: 'Перша екранізація культової книги, що показує вступ Гаррі до Гоґвортсу. Його знайомство з друзями і світом магії. Прем\'єра відбулась у 2001 році і стала однією темою.',
    differences: [
      {
        id: 'hp-1-d1',
        title: 'Перше знайомство з Драко Малфоєм',
        bookText: 'Гаррі знайомиться з Драко ще до школи — у магазині мантій Madam Malkin\'s. Це знайомство показує характер Малфоя ще до потрапляння в Гоґвортс.',
        filmText: 'У фільмі ця сцена відсутня. Перше знайомство відбувається вже у замку, коли Гаррі та Рон приходять до великої зали.',
        isSpoiler: false,
      },
      {
        id: 'hp-1-d2',
        title: 'Поминальний бенкет на честь Гаррі',
        bookText: 'У книзі багато діалогів між учнями про Поттера, і Гаррі сидить у напівтемряві.',
        filmText: 'У фільмі ефектне сповільнене панорамування над великою залою.',
        isSpoiler: false,
      },
      {
        id: 'hp-1-d3',
        title: 'Зустріч із Норбертом',
        bookText: 'Гаррі, Рон і Герміона довго возилися із Норбертом — драконом Гаґріда. Цей сюжет займає кілька розділів.',
        filmText: 'Норберта прибрали з фільму повністю — щоб скоротити хронометраж.',
        isSpoiler: true,
      },
      {
        id: 'hp-1-d4',
        title: 'Дзеркало Яцрес',
        bookText: 'Описано детально, як Гаррі провів багато ночей перед дзеркалом, бачачи свою сім\'ю.',
        filmText: 'У фільмі — одна сцена з матір\'ю та батьком, без розгорнутої лінії.',
        isSpoiler: false,
      },
      {
        id: 'hp-1-d5',
        title: 'Фінальна боротьба з Кваррелом',
        bookText: 'У книзі Гаррі сам спалює Кваррела дотиком долонь — Волдеморт відступає.',
        filmText: 'У фільмі сцена показана більш візуально — обличчя Кваррела розсипається на попіл.',
        isSpoiler: true,
      },
    ],
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    title: 'Володар перснів: Братство персня',
    year: 2001,
    genre: 'Фентезі',
    country: 'США',
    poster:
      'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg',
    bookRating: 9.8,
    filmRating: 9.1,
    description: 'Хобіт Фродо вирушає у небезпечну подорож, щоб знищити Єдиний Перстень.',
    author: 'J. R. R. Tolkien',
    hasMap: true,
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    title: 'Дюна',
    year: 2021,
    genre: 'Фантастика',
    country: 'США',
    poster:
      'https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg',
    bookRating: 9.5,
    filmRating: 8.8,
    description: 'Пол Атрейдес прибуває на пустельну планету Арракіс — єдине джерело найціннішої речовини.',
    author: 'Frank Herbert',
    hasMap: false,
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    title: 'Мартін Іден',
    year: 2019,
    genre: 'Драма',
    country: 'Італія',
    poster: 'https://m.media-amazon.com/images/M/MV5BMjAyMDMxNTk4NF5BMl5BanBnXkFtZTgwNjg5NjQ4NzM@._V1_SX300.jpg',
    bookRating: 9.0,
    filmRating: 8.3,
    description: 'Молодий моряк прагне стати письменником заради кохання та визнання.',
    author: 'Jack London',
    hasMap: false,
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    title: 'Хрещений батько',
    year: 1972,
    genre: 'Кримінал',
    country: 'США',
    poster:
      'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    bookRating: 9.1,
    filmRating: 9.7,
    description: "Сага про могутню мафіозну сім'ю Корлеоне і боротьбу за владу.",
    author: 'Mario Puzo',
    hasMap: true,
  },
  {
    id: '66666666-6666-6666-6666-666666666666',
    title: 'Убити пересмішника',
    year: 1962,
    genre: 'Драма',
    country: 'США',
    poster:
      'https://m.media-amazon.com/images/M/MV5BNmVmYzcwNjgtMzQxYS00NTZkLTkxNjEtMWQzNzIxZTYwMGQ1XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    bookRating: 9.4,
    filmRating: 8.9,
    description: 'Адвокат на Півдні США захищає чорношкірого чоловіка, несправедливо звинуваченого.',
    author: 'Harper Lee',
    hasMap: false,
  },
];
