/**
 * Усі видимі рядки UI — в одному місці (Етап 2, Крок 2 — Локалізація).
 *
 * Це проміжний крок до повноцінного i18n (vue-i18n). Поки додаток одномовний
 * (українська), ми просто винесли тексти з шаблонів у константи.
 */

export const STR = {
  /* ───────────── Common ───────────── */
  common: {
    loading: 'Завантаження…',
    retry: 'Повторити',
    cancel: 'Скасувати',
    confirm: 'Підтвердити',
    delete: 'Видалити',
    edit: 'Редагувати',
    save: 'Зберегти',
    submit: 'Надіслати',
    close: 'Закрити',
    notFound: 'Нічого не знайдено',
    serverDown: 'Backend недоступний. Дані не завантажуються.',
    sessionExpired: 'Сесія закінчилась — увійдіть знову',
    accessDenied: 'Немає доступу до цього ресурсу',
    networkError: 'Сервер недоступний. Перевірте інтернет або спробуйте пізніше.',
    unknownError: 'Невідома помилка',
    search: 'Пошук...',
    searchSubmit: 'Шукати',
    filters: '⚙ Фільтри',
    closeFilters: 'Закрити фільтри',
    showMore: 'Показати більше',
    back: 'Назад',
  },

  /* ───────────── Auth ───────────── */
  auth: {
    loginTitle: 'Вхід',
    registerTitle: 'Реєстрація',
    resetTitle: 'Відновлення паролю',
    login: 'Логін',
    loginPlaceholder: 'Введіть логін',
    email: 'Email',
    emailPlaceholder: 'Введіть Email',
    password: 'Пароль',
    passwordPlaceholder: 'Введіть пароль',
    passwordRepeat: 'Повторіть пароль',
    submitLogin: 'Ввійти',
    submitting: 'Вхід...',
    submitRegister: 'Зареєструватись',
    submittingRegister: 'Реєстрація...',
    submitReset: 'Відновити',
    submittingReset: 'Відновлення...',
    forgotPassword: 'Забули пароль?',
    sendCode: 'Надіслати код',
    sending: '...',
    codeSentTo: (email: string) => `Код надіслано на ${email}`,
    codeLabel: 'Код',
    codePlaceholder: 'Введіть код',
    resetEmailLabel: 'Введіть Email для відновлення паролю',
    invalidEmail: 'Введіть коректний email',
    emptyLogin: 'Введіть логін',
    emptyPassword: 'Введіть пароль',
    passwordTooShort: 'Пароль має бути не менше 8 символів',
    passwordsMismatch: 'Паролі не співпадають',
    emptyCode: 'Введіть код',
    logoutTooltip: (email: string) => `Вийти (${email})`,
    loginTooltip: 'Вхід',
    logout: 'Вийти',
  },

  /* ───────────── Home ───────────── */
  home: {
    heroAlt: 'Книга чи фільм – що краще?',
    heroBtn: 'Переглянути',
    heroBtnAccent: 'ТОП',
    popularTitle: 'Популярні порівняння',
  },

  /* ───────────── Top ───────────── */
  top: {
    title: 'Найкращі адаптації',
    bestTitle: 'Найкращі адаптації',
    worstTitle: 'Найгірші адаптації',
    yearOption: 'Рік виходу',
    genreOption: 'Оберіть жанр',
    onlyWithMap: 'Лише з картою відмінностей',
    emptyByFilters: 'За обраними фільтрами нічого не знайдено',
  },

  /* ───────────── Detail ───────────── */
  detail: {
    notFound: 'Елемент не знайдено',
    bookYear: 'Рік:',
    bookGenre: 'Жанр:',
    bookCountry: 'Країна:',
    bookAuthor: 'Автор:',
    bookDirector: 'Режисер:',
    bookRating: 'Рейтинг:',
    summaryTitle: 'Коротка анотація',
    wantToRead: 'Хочу прочитати',
    wantToWatch: 'Хочу переглянути',
    inList: 'У списку',
    adapted: 'Екранізовано',
    bookRatingLabel: 'Оцінка книги',
    filmRatingLabel: 'Оцінка екранізації',
    differencesTitle: 'Карта відмінностей',
    voteTitle: 'Що, на вашу думку, вдалося краще?',
    voteBook: 'Книга',
    voteFilm: 'Фільми',
    voteVs: 'VS',
    voteThanks: 'Дякуємо за ваш голос!',
    voteNeedAuth: 'Увійдіть, щоб голосувати',
    voteLoadingResults: 'Завантажуємо результати…',
    voteTotal: (n: number) => `Всього голосів: ${n}`,
    spoilerWarning: '⚠ Цей пункт містить спойлер',
    spoilerReveal: 'Показати',
    commentsTitle: 'Коментарі',
    commentPlaceholder: 'Залиште коментар',
    commentNeedAuth: 'Увійдіть, щоб написати відгук',
    commentEmpty: 'Введіть текст відгуку',
    commentEmptyList: 'Будьте першим, хто залишить відгук',
    commentPublished: 'Відгук опубліковано',
    markSpoiler: 'Позначити як спойлер',
    commentContainsSpoiler: 'Коментар містить спойлер,',
    commentShow: 'показати',
    reportBtn: 'Поскаржитись',
    wishlistNeedAuth: 'Увійдіть, щоб додавати до списку',
    ratingNeedAuth: 'Увійдіть, щоб ставити оцінку',
  },

  /* ───────────── Profile ───────────── */
  profile: {
    title: 'Ваш профіль',
    usernameTitle: "Ім'я користувача:",
    statsTitle: 'Статистика активності:',
    changePhoto: 'Змінити фото',
    username: 'Username:',
    birthDate: 'Дата народження:',
    email: 'Електронна пошта:',
    name: "Ім'я",
    statsReviews: 'Відгуки:',
    statsRatings: 'Оцінки:',
    statsWatched: 'Переглянуто:',
    myRatingsTitle: '⭐ Мої оцінки',
    myReviewsTitle: '💬 Мої відгуки',
    wishlistTitle: 'Список «Хочу переглянути/прочитати»',
    yourRating: 'Ваша оцінка',
    reviewText: 'Текст відгуку:',
    noRatings: 'Ви ще не поставили жодної оцінки',
    noReviews: 'У вас ще немає відгуків',
    noWishlist: 'Ви ще нічого не додали в список',
    avatarTooLarge: 'Розмір файлу не має перевищувати 1 МБ',
    profileUpdated: 'Профіль оновлено',
    avatarUpdated: 'Фото оновлено',
    reviewDeleted: 'Відгук видалено',
    view: 'Переглянути',
    logout: 'Вийти',
  },

  /* ───────────── Admin ───────────── */
  admin: {
    panelTitle: 'Адмін-панель',
    moderationTitle: 'Модерація коментарів',
    addBookTitle: 'Додавання твору',
    editBookTitle: 'Редагування твору',
    addBook: 'Додати книгу',
    moderation: 'Модерація коментарів',
    bookDeleted: 'Книгу видалено',
    bookUpdated: 'Книгу оновлено',
    bookAdded: 'Книгу додано',
    fillTitleAndYear: 'Заповніть назву і рік',
    confirmDelete: (title: string) => `Видалити "${title}"?`,
    searchPlaceholder: 'Пошук за назвою / автором / роком…',
    backToBooks: '← До списку творів',
    bookFormSectionTitle: 'Заповніть інформацію про книгу',
    mapSectionTitle: 'Заповніть інтерактивну карту відмінностей',
    addPoint: '+ Додати нову точку',
    point: (n: number) => `Точка ${n}`,
    noPoints: 'Точок ще немає. Натисніть "Додати точку".',
    titleLabel: 'Назва',
    authorLabel: 'Автор',
    yearLabel: 'Рік виходу',
    genreLabel: 'Жанр',
    countryLabel: 'Країна',
    posterLabel: 'URL зображення (постер)',
    descriptionLabel: 'Короткий опис',
    bookRatingLabel: 'Рейтинг книги (0–10)',
    filmRatingLabel: 'Рейтинг екранізації (0–10)',
    pointTitle: 'Заголовок',
    sceneBook: 'Сцена в книзі',
    sceneFilm: 'Сцена в фільмі',
    spoiler: 'Спойлер',
    posterPreviewAlt: "Прев'ю",
    chooseGenre: '— оберіть —',
    saving: 'Збереження…',
    reasonHeader: 'Причина',
    commentHeader: 'Коментар',
    actionHeader: 'Дія',
    approve: 'Схвалити',
    markSpoiler: 'Спойлер',
    noReports: 'Скарг немає',
    commentDeleted: 'Коментар видалено',
    reportRejected: 'Скаргу відхилено',
    markedSpoiler: 'Позначено як спойлер',
    idHeader: 'ID',
    titleHeader: 'Назва',
    yearHeader: 'Рік',
    nothingFound: 'Нічого не знайдено',
  },

  /* ───────────── Report modal ───────────── */
  report: {
    title: 'Поскаржитись на коментар',
    reasonLabel: 'Вкажіть причину',
    chooseReason: '— оберіть —',
    reasonRequired: 'Оберіть причину',
    sending: 'Надсилаємо…',
    submitted: 'Скаргу надіслано на модерацію',
  },

  /* ───────────── Search ───────────── */
  search: {
    pageTitle: 'Результати пошуку',
    queryLabel: 'Запит:',
    foundLabel: (n: number) => ` · Знайдено: ${n}`,
  },
};
