// <copyright file="20260605000001_AddPerformanceIndexes_Designer.cs" company="Team 17">
// Copyright (c) Team 17. All rights reserved.
// </copyright>

// <auto-generated />
using System;
using Book2Screen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Book2Screen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605000001_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // NOTE: Цей файл є snapshot цільової моделі після застосування міграції.
            // Повний опис моделі збігається з ApplicationDbContextModelSnapshot.cs
            // із додатковими індексами, визначеними в Up() цієї міграції.
#pragma warning restore 612, 618
        }
    }
}
